language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-1.13
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test
deploy:
  provider: npm
  email: null@ember.theater
  api_key:
    secure: ciD877L8hhk3jsZ0COxCqJa3TneU7IZbWEL+8t4cKRdVqqE4zagUFXcAjR5mDnQfkSFz7zQkLpa92DGobhoRQ/OJWciBYFDIzi8jKVExE66IpZpKBWVEVSHo1+EcOLGtSY7w3irn/9WV6ejUEp0smAR/BG1RLQxaD/dtcJJBaib1s2fqqb8bBAIN8xoRkaN8DjYTfTdQCoHDoGeRFtf0UD8RiSJUICjJPlv01FrxN0Buk9xHwWv5pKNuMPhhbmIjZ0xDuF1P8RyfcmHAf95/lyCvOMpriPUNSFOxwcmWmR2Pl+8eATri7dAD/Nf3nKvQpgiPMRQMRl2p3QkpCO6Fn3qTOATMYDavmqxWFi6pvDDYpCBABE9gZNXW9RSeY41ofbJjk7UwoxSEwAxNHKRLa2NlZfyfBV797qSZmscklv1nuoK4rV0MyuV35YV7Jmm+DPEn8MyYigy3/Q9Yz21MqJRI1/kAvq/w8dkOpOrkBD64mkTY+zQaNJkchGjKoVUcG9YzeQasdHq80F4ivxstHrRaswiWDevYphU38bGeQGTIBMrC4razGb5tsoqeHRAXQhN9LQVoEbZ8f/+zXKbqq6nYB16DPPNxNib3toEGscxgfhinKsi4T+iGvrfKiJGWVqxczW4rW8mM5/vTKE/I59kcwO8F2Mhb5VUt2b5V8VI=
  on:
    tags: true
    repo: null-null-null/ember-perfect-scrollbar
