language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-1.13
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: npm
  email: null@affinitygamescollective.org
  api_key:
    secure: P6pBvMwHKsjib970DMkl4cvJbt5S2H3dYTSlAlNf2bHFnXuwx1KFIYoNRs2D42c0A6kIrD7fEZSI6O2Egj+I6lBxlq5km9DgrAnwusMGAke7A78yBtJvC1Cs+nwYl70Fj69Xz+W+idwy6iYKwxNqbj3gIm85WtsEH+DaCRgP0tv4k8We5S6wsKtR7alH55Mt3ZIw3Q+AbVXzCMAu/VDQmUZwN6UO8RZ3M7gRxHMDO6XsClf/OY/RGzUSTR4v9fctyebovniOt6zVx0duXDKxoBb5/x/PEThihngaUPNq6Zb7SNGVoxHshBEtIOSMenkalN+G+cBQdr0GkAGGCvjYfMOwYAE79Oa6TGkumvEwKpqULxra/ihDNg5Zw/ICQoqyhE76oYLsIOWy838h3dEApoCr8SF7hOkvYXrl04xggtcqAsMCwcf93YROZ0feyCcBPMKmE7cPvwZTpUXYpskiekm1gsG4fM0iHocOEKrDirEP3nW3A6tWbIuWLzeVn2DC5Zysra7BB/3Z7fLgJxUkMR+Lj5MqGqPT0kfhrI8Hrey9q7PbvG5BKe9XZIk8GNRPELtb8IKiDPL55rQz3r+5AUQT9t2HF1M3qI0yu7d9vS+NUgz3h4Vk13gMkAqeBcYwuEd/rRp6R9YICS3dU78XTiIgN3vdSKzkuN+KIj+mTmw=
  on:
    tags: true
    repo: null-null-null/ember-perfect-scrollbar
